version: '3'
services:
  web:
    build:
      context: .
    container_name: web-server
    image: web
    ports:
      - 80:80
    volumes:
      - ./src/laravel:/var/www/laravel
      - ./src/sites-available:/etc/apache2/sites-available

