version: '3'
services:
  web:
    build:
      context: .
    container_name: web-server
    image: web
    ports:
      - 80:80
    volumes:
      - ./src/www:/var/www
      - ./src/apache2:/etc/apache2

