version: '3'
services:
  web:
    build:
      context: .
    container_name: web-server
    image: web
    ports:
      - 80:80
    volumes:
      - ./src/www/laravel:/var/www/laravel
      #- ./src/default.conf:/etc/apache2/sites-enabled/000-default.conf

